# Generated by Django 3.0.3 on 2020-03-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='closed_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'canceled'), ('Completed', 'completed'), ('Waiting', 'waiting'), ('In progress', 'in progress')], default='Waiting', max_length=50),
        ),
    ]
