# Generated by Django 3.0.3 on 2020-03-12 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200313_0217'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='car',
            new_name='car_id',
        ),
    ]
