# Generated by Django 3.0.3 on 2020-03-13 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200313_0135'),
        ('orders', '0005_auto_20200313_0239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='car_id',
        ),
        migrations.AddField(
            model_name='order',
            name='car',
            field=models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='account.Car'),
            preserve_default=False,
        ),
    ]
