# Generated by Django 3.0.3 on 2020-03-13 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200313_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='closed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
