# Generated by Django 3.0.3 on 2020-03-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20200313_0135'),
        ('orders', '0008_auto_20200313_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(default='Undefined', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='account.Profile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Canceled'), ('Completed', 'Completed'), ('Waiting', 'Waiting'), ('In progress', 'In progress')], default='Waiting', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('Live support', 'Live support'), ('Repair service', 'Repair service'), ('Complete care', 'Complete care'), ('Spare parts', 'Spare parts'), ('Sales service', 'Sales service'), ('Tyre service', 'Tyre service'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
