# Generated by Django 3.0.3 on 2020-03-14 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profile',
        ),
    ]
