# Generated by Django 3.0.3 on 2020-03-14 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200314_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('In progress', 'In progress'), ('Completed', 'Completed'), ('Cancelled', 'Canceled')], default='Waiting', max_length=50),
        ),
    ]
