# Generated by Django 3.0.3 on 2020-03-16 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_orderdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_dates', to='orders.OrderDate'),
        ),
    ]
