# Generated by Django 3.0.3 on 2020-03-09 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
